[project]
name = "connect-to-qqq100-index-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai>=1.7.0",
    "langchain-community>=0.4.1",
    "yfinance>=0.2.66",
]
